## Import Library

In [105]:
# !pip install torchviz

In [106]:
import torch
import torch.nn as nn
import torchvision
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm
from collections import OrderedDict
from torchviz import make_dot

## Pembuatan Kelas Autoencoder

In [107]:
class autoencoder(nn.Module):
    def __init__(self):
        super().__init__()
        layers = [
            (
                "conv2d_1",
                nn.Conv2d(in_channels=1, out_channels=2, kernel_size=3, stride=1, padding=0),
            ),
            (
                "conv2d_2",
                nn.Conv2d(2, 2, kernel_size=3, stride=2, padding=0),
            ),
            (
                "ReLU_1",
                nn.ReLU(2),
            ),
            (
                "convtrans2d_1",
                nn.ConvTranspose2d(2, 1, kernel_size=3, stride=2, padding=0),
            ),
            (
                "convtrans2d_2",
                nn.ConvTranspose2d(1, 1, kernel_size=3, stride=1, padding=0),
            ),
            (
                "ReLU_2",
                nn.ReLU(1),
            )
        ]
        self.model = nn.Sequential(OrderedDict(layers))

        def forward(self, x):
            return self.model(x)

    def forward(self, x):
        return self.model(x)

In [108]:
model = autoencoder()
model

autoencoder(
  (model): Sequential(
    (conv2d_1): Conv2d(1, 2, kernel_size=(3, 3), stride=(1, 1))
    (conv2d_2): Conv2d(2, 2, kernel_size=(3, 3), stride=(2, 2))
    (ReLU_1): ReLU(inplace=True)
    (convtrans2d_1): ConvTranspose2d(2, 1, kernel_size=(3, 3), stride=(2, 2))
    (convtrans2d_2): ConvTranspose2d(1, 1, kernel_size=(3, 3), stride=(1, 1))
    (ReLU_2): ReLU(inplace=True)
  )
)

## Inisialisasi Bobot dan Bias Kernel 1

In [109]:
# inisialisasi bobot kernel 1

conv2d_1_weight = torch.Tensor(
    [
        [[[2, 0, 2], [0, 2, 0], [2, 0, 2]]],
        [[[1, 0, 1], [1, 0, 1], [1, 1, 1]]]
    ]
)

conv2d_1_weight.requires_grad = True
conv2d_1_weight

tensor([[[[2., 0., 2.],
          [0., 2., 0.],
          [2., 0., 2.]]],


        [[[1., 0., 1.],
          [1., 0., 1.],
          [1., 1., 1.]]]], requires_grad=True)

In [110]:
model.model.conv2d_1.weight = nn.Parameter(conv2d_1_weight)

print(model.model.conv2d_1.weight)
print(model.model.conv2d_1.weight.shape)

Parameter containing:
tensor([[[[2., 0., 2.],
          [0., 2., 0.],
          [2., 0., 2.]]],


        [[[1., 0., 1.],
          [1., 0., 1.],
          [1., 1., 1.]]]], requires_grad=True)
torch.Size([2, 1, 3, 3])


In [111]:
# bias kernel 1
conv2d_1_bias = torch.Tensor([1, 2])
conv2d_1_bias.requires_grad = True
conv2d_1_bias

tensor([1., 2.], requires_grad=True)

In [112]:
model.model.conv2d_1.bias = nn.Parameter(
    conv2d_1_bias
)
print(model.model.conv2d_1.bias)

Parameter containing:
tensor([1., 2.], requires_grad=True)


## Inisialisasi Bobot dan Bias Kernel 2

In [113]:
# inisialisasi bobot kernel 2
conv2d_2_weight = torch.Tensor(
    [
        [[[1, 0, 1], [1, 1, 1], [0, 0, 0]]],
        [[[1, 1, 0], [0, 0, 1], [1, 1, 0]]],
        [[[2, 2, 0], [0, 2, 2], [-2, -1, 0]]],
        [[[0, 0, 1], [1, 0, 0], [1, 1, 0]]]
    ]
)

conv2d_2_weight = conv2d_2_weight.view(2, 2, 3, 3)
conv2d_2_weight.requires_grad = True

print(conv2d_2_weight)
print(conv2d_2_weight.shape)

tensor([[[[ 1.,  0.,  1.],
          [ 1.,  1.,  1.],
          [ 0.,  0.,  0.]],

         [[ 1.,  1.,  0.],
          [ 0.,  0.,  1.],
          [ 1.,  1.,  0.]]],


        [[[ 2.,  2.,  0.],
          [ 0.,  2.,  2.],
          [-2., -1.,  0.]],

         [[ 0.,  0.,  1.],
          [ 1.,  0.,  0.],
          [ 1.,  1.,  0.]]]], requires_grad=True)
torch.Size([2, 2, 3, 3])


In [114]:
model.model.conv2d_2.weight = nn.Parameter(conv2d_2_weight)

print(model.model.conv2d_2.weight)
print(model.model.conv2d_2.weight.shape)

Parameter containing:
tensor([[[[ 1.,  0.,  1.],
          [ 1.,  1.,  1.],
          [ 0.,  0.,  0.]],

         [[ 1.,  1.,  0.],
          [ 0.,  0.,  1.],
          [ 1.,  1.,  0.]]],


        [[[ 2.,  2.,  0.],
          [ 0.,  2.,  2.],
          [-2., -1.,  0.]],

         [[ 0.,  0.,  1.],
          [ 1.,  0.,  0.],
          [ 1.,  1.,  0.]]]], requires_grad=True)
torch.Size([2, 2, 3, 3])


In [115]:
# bias kernel 2
conv2d_2_bias = torch.Tensor([0, 0])
conv2d_2_bias.requires_grad = True
conv2d_2_bias

tensor([0., 0.], requires_grad=True)

In [116]:
model.model.conv2d_2.bias = nn.Parameter(conv2d_2_bias)
print(model.model.conv2d_2.bias)

Parameter containing:
tensor([0., 0.], requires_grad=True)


## Inisialisasi Bobot dan Bias Kernel 3


In [117]:
# inisialisasi bobot kernel 3
convtrans2d_1_weight = torch.Tensor(
    [
        [[[3, 0, 3], [3, 1, -1], [0, 0, 1]]],
        [[[2, 1, 0], [0, 0, 1], [-1, 0, 1]]]
    ]
)

convtrans2d_1_weight.requires_grad = True
print(convtrans2d_1_weight)

tensor([[[[ 3.,  0.,  3.],
          [ 3.,  1., -1.],
          [ 0.,  0.,  1.]]],


        [[[ 2.,  1.,  0.],
          [ 0.,  0.,  1.],
          [-1.,  0.,  1.]]]], requires_grad=True)


In [118]:
model.model.convtrans2d_1.weight = nn.Parameter(convtrans2d_1_weight)

print(model.model.convtrans2d_1.weight)
print(model.model.convtrans2d_1.weight.shape)

Parameter containing:
tensor([[[[ 3.,  0.,  3.],
          [ 3.,  1., -1.],
          [ 0.,  0.,  1.]]],


        [[[ 2.,  1.,  0.],
          [ 0.,  0.,  1.],
          [-1.,  0.,  1.]]]], requires_grad=True)
torch.Size([2, 1, 3, 3])


In [119]:
# bias kernel 3
convtrans2d_1_bias = torch.Tensor([0])
convtrans2d_1_bias.requires_grad = True
convtrans2d_1_bias

tensor([0.], requires_grad=True)

In [120]:
model.model.convtrans2d_1.bias = nn.Parameter(convtrans2d_1_bias)
print(model.model.convtrans2d_1.bias)

Parameter containing:
tensor([0.], requires_grad=True)


## Inisialisasi Bobot dan Bias Kernel 4


In [121]:
# inisialisasi bobot kernel 4
convtrans2d_2_weight = torch.Tensor(
    [
        [[[1, 1, 0], [0, 0, -1], [0, 0, 0]]]
    ]
)

convtrans2d_2_weight.requires_grad = True
print(convtrans2d_2_weight)

tensor([[[[ 1.,  1.,  0.],
          [ 0.,  0., -1.],
          [ 0.,  0.,  0.]]]], requires_grad=True)


In [122]:
model.model.convtrans2d_2.weight = nn.Parameter(convtrans2d_2_weight)

print(model.model.convtrans2d_2.weight)
print(model.model.convtrans2d_2.weight.shape)

Parameter containing:
tensor([[[[ 1.,  1.,  0.],
          [ 0.,  0., -1.],
          [ 0.,  0.,  0.]]]], requires_grad=True)
torch.Size([1, 1, 3, 3])


In [123]:
# bias kernel 4
convtrans2d_2_bias = torch.Tensor([1])
convtrans2d_2_bias.requires_grad = True
convtrans2d_2_bias

tensor([1.], requires_grad=True)

In [124]:
model.model.convtrans2d_2.bias = nn.Parameter(convtrans2d_2_bias)
print(model.model.convtrans2d_2.bias)

Parameter containing:
tensor([1.], requires_grad=True)


## Pengujian Model

In [125]:
input = torch.Tensor(
    [
        [[1, 0, 0, 1, 0], [0, 0, 0, 1, 0], [1, 0, 1, 0, 1], [1, 1, 1, 0, 1], [0, 1, 0, 1, 0]]
    ]
)

optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
output = model(input)
output

tensor([[[270., 316., 224., 178.,   1.],
         [178., 237.,   0.,   0.,   0.],
         [  0.,   0.,   0.,  47.,  14.],
         [  1.,   1.,  47.,   1.,   0.],
         [  1.,   1.,   1.,   1.,   1.]]], grad_fn=<AsStridedBackward0>)

In [126]:
x = input
print("Input")
print(x)
for i in model.model:
    x = i(x)
    print(i)
    print(x)

Input
tensor([[[1., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0.],
         [1., 0., 1., 0., 1.],
         [1., 1., 1., 0., 1.],
         [0., 1., 0., 1., 0.]]])
Conv2d(1, 2, kernel_size=(3, 3), stride=(1, 1))
tensor([[[7., 3., 7.],
         [5., 7., 5.],
         [7., 7., 5.]],

        [[5., 5., 4.],
         [7., 5., 6.],
         [7., 5., 7.]]], grad_fn=<SqueezeBackward1>)
Conv2d(2, 2, kernel_size=(3, 3), stride=(2, 2))
tensor([[[59.]],

        [[46.]]], grad_fn=<SqueezeBackward1>)
ReLU(inplace=True)
tensor([[[59.]],

        [[46.]]], grad_fn=<AsStridedBackward0>)
ConvTranspose2d(2, 1, kernel_size=(3, 3), stride=(2, 2))
tensor([[[269.,  46., 177.],
         [177.,  59., -13.],
         [-46.,   0., 105.]]], grad_fn=<SqueezeBackward1>)
ConvTranspose2d(1, 1, kernel_size=(3, 3), stride=(1, 1))
tensor([[[ 270.,  316.,  224.,  178.,    1.],
         [ 178.,  237., -222.,  -58., -176.],
         [ -45.,  -45.,  -71.,   47.,   14.],
         [   1.,    1.,   47.,    1., -104.],
       

## Pengujian Model untuk nilai Loss

In [127]:
loss = (( output - input ) ** 2).sum()
loss.backward()
optimizer.step()

(( output - input ) ** 2).sum()

tensor(346078., grad_fn=<SumBackward0>)

In [131]:
# Hasil konvolusi
for i in model.model:
    if not isinstance(i, nn.ReLU):
        print(i)
        print(i.weight.grad)
        print(i.bias.grad)

Conv2d(1, 2, kernel_size=(3, 3), stride=(1, 1))
tensor([[[[ 8906., 21392., 16066.],
          [14232., 14232., 24972.],
          [62430., 24972., 46364.]]],


        [[[21392., 24972., 21392.],
          [37458., 28552., 33878.],
          [37458., 24972., 37458.]]]])
tensor([62430., 58850.])
Conv2d(2, 2, kernel_size=(3, 3), stride=(2, 2))
tensor([[[[62342., 26718., 62342.],
          [44530., 62342., 44530.],
          [62342., 62342., 44530.]],

         [[44530., 44530., 35624.],
          [62342., 44530., 53436.],
          [62342., 44530., 62342.]]],


        [[[25060., 10740., 25060.],
          [17900., 25060., 17900.],
          [25060., 25060., 17900.]],

         [[17900., 17900., 14320.],
          [25060., 17900., 21480.],
          [25060., 17900., 25060.]]]])
tensor([8906., 3580.])
ConvTranspose2d(2, 1, kernel_size=(3, 3), stride=(2, 2))
tensor([[[[69030., 63720., 47318.],
          [48970., 22420., -1534.],
          [-5428.,  -118.,  5546.]]],


        [[[53820., 49

In [132]:
# Update bobot dan bias setiap kernel
print("Nilai dari update bobot dan bias setiap kernel: \n")
for i in model.model:
    if not isinstance(i, nn.ReLU):
        print(i)
        print(i.weight)
        print(i.bias)

Nilai dari update bobot dan bias setiap kernel: 

Conv2d(1, 2, kernel_size=(3, 3), stride=(1, 1))
Parameter containing:
tensor([[[[ -6.9060, -21.3920, -14.0660],
          [-14.2320, -12.2320, -24.9720],
          [-60.4300, -24.9720, -44.3640]]],


        [[[-20.3920, -24.9720, -20.3920],
          [-36.4580, -28.5520, -32.8780],
          [-36.4580, -23.9720, -36.4580]]]], requires_grad=True)
Parameter containing:
tensor([-61.4300, -56.8500], requires_grad=True)
Conv2d(2, 2, kernel_size=(3, 3), stride=(2, 2))
Parameter containing:
tensor([[[[-61.3420, -26.7180, -61.3420],
          [-43.5300, -61.3420, -43.5300],
          [-62.3420, -62.3420, -44.5300]],

         [[-43.5300, -43.5300, -35.6240],
          [-62.3420, -44.5300, -52.4360],
          [-61.3420, -43.5300, -62.3420]]],


        [[[-23.0600,  -8.7400, -25.0600],
          [-17.9000, -23.0600, -15.9000],
          [-27.0600, -26.0600, -17.9000]],

         [[-17.9000, -17.9000, -13.3200],
          [-24.0600, -17.9000, -